name: AWS GPU

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, aws-gpu] # aws-gpu == label in cirun.yml
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Nvidia SMI sanity check
        run: nvidia-smi

      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: "1.3.1-0"
          environment-name: anndata-gpu-ci
          create-args: >-
            python=3.10
            cupy
          init-shell: >-
            bash
          generate-run-shell: false

      - name: Install AnnData
        run: pip install .[dev,test]

      - name: Mamba list
        run: micromamba list

      - name: Run test
        run: python3 -c 'import anndata, cupyx; cupyx.scipy.sparse.random(100, 50, format="csr")'
